---
- name: settingup apache2 on ubuntu
  hosts: g2
  become: yes

  tasks:
  - name: installing apache2
    apt:
      name: apache2
      state: present

  - name: starting apache2
    service:
      name: apache2
      state: started

  - name: enabling apache2
    service:
      name: apache2
      enabled: yes


...
